# This file is a WIP
version: '3.2'
services:
  skilloracle:
    image: skilloracle:latest
    build:
      context: ./
      dockerfile: ./skilloracle/Dockerfile
    depends_on:
        - redis
    tty: true
  redis:
    image: redis
